import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext(null);
const LANGUAGE_KEY = 'topline_language';

const swahili = {
  'Home': 'Nyumbani', 'People': 'Watu', 'Create': 'Tengeneza', 'Inbox': 'Ujumbe', 'Profile': 'Wasifu', 'Alerts': 'Arifa',
  'Settings': 'Mipangilio', 'Back': 'Rudi', 'Account': 'Akaunti', 'No email': 'Hakuna barua pepe',
  'Appearance': 'Mwonekano', 'Dark mode': 'Hali ya giza', 'Light mode': 'Hali ya mwanga', 'Applies across the entire app': 'Inatumika kwenye programu nzima',
  'Language': 'Lugha', 'Choose your preferred language': 'Chagua lugha unayopendelea', 'English': 'Kiingereza', 'Kiswahili': 'Kiswahili',
  'Edit Profile': 'Hariri wasifu', 'Log Out': 'Ondoka', 'Log out': 'Ondoka', 'Are you sure you want to log out?': 'Una uhakika unataka kuondoka?', 'Cancel': 'Ghairi',
  'Toggle dark mode': 'Washa au zima hali ya giza', 'Select language': 'Chagua lugha', 'Close language selection': 'Funga uchaguzi wa lugha',
  'Welcome back': 'Karibu tena', 'Sign in to continue to Topline.': 'Ingia ili kuendelea na Topline.', 'Connect. Share. Stay informed.': 'Ungana. Shiriki. Pata habari.',
  'Email or Username': 'Barua pepe au jina la mtumiaji', 'Enter your email or username': 'Weka barua pepe au jina lako la mtumiaji',
  'Password': 'Nenosiri', 'Enter your password': 'Weka nenosiri lako', 'Signing In...': 'Inaingia...', 'Sign In': 'Ingia', 'Create Account': 'Fungua akaunti',
  'Missing information': 'Taarifa hazijakamilika', 'Please enter your email/username and password.': 'Weka barua pepe/jina la mtumiaji na nenosiri.',
  'Login failed': 'Kuingia kumeshindikana', 'Unable to log in.': 'Imeshindikana kuingia.',
  'Create your account': 'Fungua akaunti yako', 'Join Topline and connect with others.': 'Jiunge na Topline na uungane na wengine.',
  'Full Name': 'Jina kamili', 'Enter your full name': 'Weka jina lako kamili', 'Username': 'Jina la mtumiaji', 'Choose a username': 'Chagua jina la mtumiaji',
  'Email': 'Barua pepe', 'Enter your email': 'Weka barua pepe yako', 'Phone': 'Simu', 'Enter your phone number': 'Weka nambari yako ya simu',
  'Date of Birth': 'Tarehe ya kuzaliwa', 'Create a password': 'Tengeneza nenosiri', 'Creating Account...': 'Inafungua akaunti...',
  'Already have an account? Sign In': 'Tayari una akaunti? Ingia', 'Please fill in all required fields.': 'Jaza sehemu zote zinazohitajika.',
  'Registration failed': 'Usajili umeshindikana', 'Unable to create your account.': 'Imeshindikana kufungua akaunti yako.',
  'Create Post': 'Tengeneza chapisho', 'Post': 'Chapisha', 'You': 'Wewe', 'Everyone can see this post': 'Kila mtu anaweza kuona chapisho hili',
  "What's on your mind?": 'Unafikiria nini?', 'Add to your post': 'Ongeza kwenye chapisho lako', 'Photo': 'Picha', 'Video': 'Video',
  'Video selected': 'Video imechaguliwa', 'Photo selected': 'Picha imechaguliwa', 'Permission required': 'Ruhusa inahitajika',
  'Allow access to your photos and videos to add media to a post.': 'Ruhusu ufikiaji wa picha na video ili kuongeza faili kwenye chapisho.',
  'Unable to open media': 'Imeshindikana kufungua faili', 'Sign in required': 'Unahitaji kuingia', 'Sign in before creating a post.': 'Ingia kabla ya kutengeneza chapisho.',
  'Post failed': 'Chapisho halikufaulu', 'Please try again.': 'Tafadhali jaribu tena.', 'Remove selected media': 'Ondoa faili lililochaguliwa',
  'Find people and connect': 'Tafuta watu na uungane nao', 'Search people...': 'Tafuta watu...',
  'People you may know': 'Watu unaoweza kuwajua', 'Discover people on Topline': 'Gundua watu kwenye Topline', 'Following': 'Unafuata', 'Follow': 'Fuata',
  'No people found': 'Hakuna watu waliopatikana', 'Try searching for another name or username.': 'Jaribu kutafuta jina au jina la mtumiaji tofauti.',
  'Messages': 'Ujumbe', 'No messages yet': 'Bado hakuna ujumbe', 'No conversations yet': 'Bado hakuna mazungumzo',
  'Your conversation with {name} will appear here.': 'Mazungumzo yako na {name} yataonekana hapa.', 'Your conversations will appear here.': 'Mazungumzo yako yataonekana hapa.', 'Find people': 'Tafuta watu',
  'You’re all caught up': 'Umesoma arifa zote', 'Likes, replies, and follows will show up here.': 'Mienendo ya kupenda, majibu na wafuatiliaji itaonekana hapa.', 'Back to feed': 'Rudi kwenye mtiririko',
  'Comments': 'Maoni', 'No comments yet': 'Bado hakuna maoni', 'Start the conversation.': 'Anzisha mazungumzo.', 'Add a comment...': 'Ongeza maoni...',
  'Delete comment?': 'Ungependa kufuta maoni?', 'This comment will be removed from the video.': 'Maoni haya yataondolewa kwenye video.', 'Delete': 'Futa',
  'Delete your comment': 'Futa maoni yako', 'Close comments': 'Funga maoni', 'Post comment': 'Chapisha maoni', 'Just now': 'Sasa hivi',
  'Topline user': 'Mtumiaji wa Topline', 'Unable to load comments.': 'Imeshindikana kupakia maoni.', 'Unable to add comment.': 'Imeshindikana kuongeza maoni.', 'Unable to delete comment.': 'Imeshindikana kufuta maoni.',
  'Choose or change profile photo': 'Chagua au badilisha picha ya wasifu', 'Change profile photo': 'Badilisha picha ya wasifu', 'Add profile photo': 'Ongeza picha ya wasifu',
  'Allow access to photos to choose a profile picture.': 'Ruhusu ufikiaji wa picha ili kuchagua picha ya wasifu.', 'Photo unavailable': 'Picha haipatikani', 'Unable to open your photos.': 'Imeshindikana kufungua picha zako.',
  'Missing info': 'Taarifa hazijakamilika', 'Name and username are required.': 'Jina na jina la mtumiaji vinahitajika.', 'Success': 'Imefanikiwa', 'Your profile has been updated.': 'Wasifu wako umesasishwa.',
  'Update failed': 'Usasishaji umeshindikana', 'Unable to update your profile.': 'Imeshindikana kusasisha wasifu wako.',
  'Tell people about yourself': 'Waambie watu kukuhusu', 'Location': 'Mahali', 'City or country': 'Jiji au nchi', 'Saving...': 'Inahifadhi...', 'Save Changes': 'Hifadhi mabadiliko',
  'Topline User': 'Mtumiaji wa Topline', 'Posts': 'Machapisho', 'Followers': 'Wafuasi', 'Message': 'Ujumbe',
  'Edit profile photo': 'Hariri picha ya wasifu', 'No posts yet': 'Bado hakuna machapisho', 'When this user shares something, it will appear here.': 'Mtumiaji akishiriki kitu, kitaonekana hapa.',
  'Recently': 'Hivi karibuni', 'For You': 'Kwa ajili yako', 'Open alerts': 'Fungua arifa', 'Open messages': 'Fungua ujumbe',
  'Go back': 'Rudi nyuma', 'Pause posted video': 'Sitisha video iliyochapishwa', 'Play posted video': 'Cheza video iliyochapishwa',
  'Topline app icon': 'Aikoni ya programu ya Topline', 'Loading...': 'Inapakia...', 'Open settings': 'Fungua mipangilio',
  'Bio': 'Wasifu mfupi', 'this person': 'mtu huyu', 'View {count} comments': 'Tazama maoni {count}',
  'A sample clip for testing video playback.': 'Klipu ya mfano ya kujaribu video.',
  'Animated trailer sample.': 'Trela ya mfano ya uhuishaji.',
  'A short animated sample clip.': 'Klipu fupi ya mfano ya uhuishaji.',
  'MP4 sample': 'Mfano wa MP4', 'Video post': 'Chapisho la video', 'Topline post': 'Chapisho la Topline',
  'Living, learning and sharing.': 'Kuishi, kujifunza na kushiriki.',
  'Creator • Photographer • Traveler': 'Mbunifu • Mpiga picha • Msafiri',
  'Technology and community.': 'Teknolojia na jamii.',
  'Making a difference every day.': 'Kuleta mabadiliko kila siku.',
  'Sign in to comment.': 'Ingia ili kutoa maoni.',
  'Your session has expired.': 'Kipindi chako cha kuingia kimeisha.',
  'Invalid post ID.': 'Kitambulisho cha chapisho si sahihi.',
  'Post not found.': 'Chapisho halijapatikana.',
  'Write a comment first.': 'Andika maoni kwanza.',
  'Comments must be 1,000 characters or fewer.': 'Maoni lazima yawe na herufi 1,000 au chini.',
  'Comment not found or you cannot delete it.': 'Maoni hayakupatikana au huwezi kuyafuta.',
  'Sign in to view your posts.': 'Ingia ili kuona machapisho yako.',
  'Email or phone required.': 'Barua pepe au nambari ya simu inahitajika.',
  'Confirmation code sent.': 'Nambari ya uthibitisho imetumwa.',
  'All fields are required.': 'Sehemu zote zinahitajika.',
  'Please provide a valid date of birth.': 'Weka tarehe sahihi ya kuzaliwa.',
  'Account created successfully.': 'Akaunti imefunguliwa kikamilifu.',
  'Something went wrong while creating the account.': 'Hitilafu imetokea wakati wa kufungua akaunti.',
  'Email/username and password are required.': 'Barua pepe/jina la mtumiaji na nenosiri vinahitajika.',
  'Incorrect email/username or password.': 'Barua pepe/jina la mtumiaji au nenosiri si sahihi.',
  'Login successful.': 'Umeingia kikamilifu.',
  'Something went wrong while logging in.': 'Hitilafu imetokea wakati wa kuingia.',
  'Unable to load posts.': 'Imeshindikana kupakia machapisho.',
  'Sign in to create a post.': 'Ingia ili kutengeneza chapisho.',
  'User account was not found.': 'Akaunti ya mtumiaji haikupatikana.',
  'Add text, a photo, or a video.': 'Ongeza maandishi, picha au video.',
  'Media uploads are not configured on the server.': 'Upakiaji wa faili haujawekwa kwenye seva.',
  'Unable to create post.': 'Imeshindikana kutengeneza chapisho.',
  'Media files must be 100 MB or smaller.': 'Faili za media lazima ziwe MB 100 au chini.',
  'Invalid media upload.': 'Upakiaji wa faili si sahihi.',
  'Invalid comment ID.': 'Kitambulisho cha maoni si sahihi.',
  'No token': 'Hakuna tokeni ya kuingia.',
  'User not found': 'Mtumiaji hakupatikana.',
  'Invalid token': 'Tokeni si sahihi.',
  'Choose a profile photo to upload.': 'Chagua picha ya wasifu ya kupakia.',
  'Profile photo uploads are not configured on the server.': 'Upakiaji wa picha za wasifu haujawekwa kwenye seva.',
  'Unable to update your profile photo.': 'Imeshindikana kusasisha picha yako ya wasifu.',
  'No valid profile fields provided': 'Hakuna sehemu halali za wasifu zilizowekwa.',
  'Profile updated successfully': 'Wasifu umesasishwa kikamilifu.',
  'Profile update failed': 'Usasishaji wa wasifu umeshindikana.',
  'Choose an image file for your profile photo.': 'Chagua faili la picha kwa picha yako ya wasifu.',
  'Invalid profile photo.': 'Picha ya wasifu si sahihi.',
  'Joined recently': 'Alijiunga hivi karibuni',
  'Open profile for {name}': 'Fungua wasifu wa {name}',
  'Invalid user ID.': 'Kitambulisho cha mtumiaji si sahihi.',
  'Unable to load profile posts.': 'Imeshindikana kupakia machapisho ya wasifu.',
};

const french = {
  'Home': 'Accueil', 'People': 'Personnes', 'Create': 'Créer', 'Inbox': 'Messages', 'Profile': 'Profil', 'Alerts': 'Alertes', 'Settings': 'Paramètres', 'Back': 'Retour',
  'Account': 'Compte', 'No email': 'Aucune adresse e-mail', 'Appearance': 'Apparence', 'Dark mode': 'Mode sombre', 'Light mode': 'Mode clair', 'Applies across the entire app': 'S’applique à toute l’application',
  'Language': 'Langue', 'Choose your preferred language': 'Choisissez votre langue préférée', 'Edit Profile': 'Modifier le profil', 'Log out': 'Se déconnecter', 'Log Out': 'Se déconnecter', 'Are you sure you want to log out?': 'Voulez-vous vraiment vous déconnecter ?', 'Cancel': 'Annuler', 'Toggle dark mode': 'Activer ou désactiver le mode sombre', 'Select language': 'Choisir la langue', 'Close language selection': 'Fermer le choix de langue',
  'Welcome back': 'Bon retour', 'Sign in to continue to Topline.': 'Connectez-vous pour continuer sur Topline.', 'Connect. Share. Stay informed.': 'Échangez. Partagez. Restez informé.', 'Email or Username': 'E-mail ou nom d’utilisateur', 'Enter your email or username': 'Saisissez votre e-mail ou nom d’utilisateur', 'Password': 'Mot de passe', 'Enter your password': 'Saisissez votre mot de passe', 'Signing In...': 'Connexion...', 'Sign In': 'Se connecter', 'Create Account': 'Créer un compte',
  'Missing information': 'Informations manquantes', 'Please enter your email/username and password.': 'Saisissez votre e-mail/nom d’utilisateur et votre mot de passe.', 'Login failed': 'Échec de la connexion', 'Unable to log in.': 'Connexion impossible.', 'Create your account': 'Créez votre compte', 'Join Topline and connect with others.': 'Rejoignez Topline et échangez avec les autres.', 'Full Name': 'Nom complet', 'Enter your full name': 'Saisissez votre nom complet', 'Username': 'Nom d’utilisateur', 'Choose a username': 'Choisissez un nom d’utilisateur', 'Email': 'E-mail', 'Enter your email': 'Saisissez votre e-mail', 'Phone': 'Téléphone', 'Enter your phone number': 'Saisissez votre numéro de téléphone', 'Date of Birth': 'Date de naissance', 'Create a password': 'Créez un mot de passe', 'Creating Account...': 'Création du compte...', 'Already have an account? Sign In': 'Vous avez déjà un compte ? Connectez-vous',
  'Please fill in all required fields.': 'Veuillez remplir tous les champs obligatoires.', 'Registration failed': 'Échec de l’inscription', 'Unable to create your account.': 'Impossible de créer votre compte.', 'Create Post': 'Créer une publication', 'Post': 'Publier', 'You': 'Vous', 'Everyone can see this post': 'Tout le monde peut voir cette publication', "What's on your mind?": 'À quoi pensez-vous ?', 'Add to your post': 'Ajouter à votre publication', 'Photo': 'Photo', 'Video': 'Vidéo', 'Video selected': 'Vidéo sélectionnée', 'Photo selected': 'Photo sélectionnée',
  'Permission required': 'Autorisation requise', 'Allow access to your photos and videos to add media to a post.': 'Autorisez l’accès à vos photos et vidéos pour les ajouter à une publication.', 'Unable to open media': 'Impossible d’ouvrir le média', 'Sign in required': 'Connexion requise', 'Sign in before creating a post.': 'Connectez-vous avant de créer une publication.', 'Post failed': 'Échec de la publication', 'Please try again.': 'Veuillez réessayer.', 'Remove selected media': 'Supprimer le média sélectionné',
  'Find people and connect': 'Trouvez des personnes et échangez', 'Search people...': 'Rechercher des personnes...', 'People you may know': 'Personnes que vous connaissez peut-être', 'Discover people on Topline': 'Découvrez des personnes sur Topline', 'Following': 'Abonné', 'Follow': 'Suivre', 'No people found': 'Aucune personne trouvée', 'Try searching for another name or username.': 'Essayez un autre nom ou nom d’utilisateur.',
  'Messages': 'Messages', 'No messages yet': 'Aucun message pour le moment', 'No conversations yet': 'Aucune conversation pour le moment', 'Your conversation with {name} will appear here.': 'Votre conversation avec {name} apparaîtra ici.', 'Your conversations will appear here.': 'Vos conversations apparaîtront ici.', 'Find people': 'Trouver des personnes', 'You’re all caught up': 'Vous êtes à jour', 'Likes, replies, and follows will show up here.': 'Les mentions J’aime, réponses et abonnements apparaîtront ici.', 'Back to feed': 'Retour au fil',
  'Comments': 'Commentaires', 'No comments yet': 'Aucun commentaire pour le moment', 'Start the conversation.': 'Lancez la conversation.', 'Add a comment...': 'Ajouter un commentaire...', 'Delete comment?': 'Supprimer le commentaire ?', 'This comment will be removed from the video.': 'Ce commentaire sera supprimé de la vidéo.', 'Delete': 'Supprimer', 'Delete your comment': 'Supprimer votre commentaire', 'Close comments': 'Fermer les commentaires', 'Post comment': 'Publier le commentaire', 'Just now': 'À l’instant', 'Topline user': 'Utilisateur Topline',
  'Unable to load comments.': 'Impossible de charger les commentaires.', 'Unable to add comment.': 'Impossible d’ajouter le commentaire.', 'Unable to delete comment.': 'Impossible de supprimer le commentaire.', 'Choose or change profile photo': 'Choisir ou modifier la photo de profil', 'Change profile photo': 'Modifier la photo de profil', 'Add profile photo': 'Ajouter une photo de profil', 'Allow access to photos to choose a profile picture.': 'Autorisez l’accès aux photos pour choisir une photo de profil.', 'Photo unavailable': 'Photo indisponible', 'Unable to open your photos.': 'Impossible d’ouvrir vos photos.', 'Missing info': 'Informations manquantes', 'Name and username are required.': 'Le nom et le nom d’utilisateur sont obligatoires.', 'Success': 'Réussite', 'Your profile has been updated.': 'Votre profil a été mis à jour.', 'Update failed': 'Échec de la mise à jour', 'Unable to update your profile.': 'Impossible de mettre à jour votre profil.',
  'Tell people about yourself': 'Parlez de vous', 'Location': 'Lieu', 'City or country': 'Ville ou pays', 'Saving...': 'Enregistrement...', 'Save Changes': 'Enregistrer les modifications', 'Topline User': 'Utilisateur Topline', 'Posts': 'Publications', 'Followers': 'Abonnés', 'Message': 'Message', 'Edit profile photo': 'Modifier la photo de profil', 'No posts yet': 'Aucune publication pour le moment', 'When this user shares something, it will appear here.': 'Les publications de cette personne apparaîtront ici.', 'Recently': 'Récemment', 'For You': 'Pour vous', 'Open alerts': 'Ouvrir les alertes', 'Open messages': 'Ouvrir les messages', 'Go back': 'Retour', 'Pause posted video': 'Mettre la vidéo en pause', 'Play posted video': 'Lire la vidéo publiée', 'Topline app icon': 'Icône de l’application Topline', 'Loading...': 'Chargement...', 'Bio': 'Biographie', 'this person': 'cette personne', 'View {count} comments': 'Voir {count} commentaires',
  'A sample clip for testing video playback.': 'Un extrait de démonstration pour tester la lecture vidéo.', 'Animated trailer sample.': 'Bande-annonce animée de démonstration.', 'A short animated sample clip.': 'Court extrait animé de démonstration.', 'MP4 sample': 'Exemple MP4', 'Video post': 'Publication vidéo', 'Topline post': 'Publication Topline', 'Living, learning and sharing.': 'Vivre, apprendre et partager.', 'Creator • Photographer • Traveler': 'Créateur • Photographe • Voyageur', 'Technology and community.': 'Technologie et communauté.', 'Making a difference every day.': 'Faire la différence chaque jour.', 'Joined recently': 'Inscrit récemment', 'Open profile for {name}': 'Ouvrir le profil de {name}',
  'Email or phone required.': 'E-mail ou téléphone requis.', 'All fields are required.': 'Tous les champs sont obligatoires.', 'Please provide a valid date of birth.': 'Veuillez saisir une date de naissance valide.', 'Account created successfully.': 'Compte créé avec succès.', 'Something went wrong while creating the account.': 'Une erreur est survenue lors de la création du compte.', 'Email/username and password are required.': 'L’e-mail/nom d’utilisateur et le mot de passe sont obligatoires.', 'Incorrect email/username or password.': 'E-mail/nom d’utilisateur ou mot de passe incorrect.', 'Something went wrong while logging in.': 'Une erreur est survenue lors de la connexion.', 'Sign in to create a post.': 'Connectez-vous pour créer une publication.', 'Your session has expired.': 'Votre session a expiré.', 'User account was not found.': 'Compte utilisateur introuvable.', 'Add text, a photo, or a video.': 'Ajoutez du texte, une photo ou une vidéo.', 'Media uploads are not configured on the server.': 'Le téléversement de médias n’est pas configuré sur le serveur.', 'Unable to create post.': 'Impossible de créer la publication.', 'Media files must be 100 MB or smaller.': 'Les fichiers multimédias doivent faire 100 Mo ou moins.', 'Invalid media upload.': 'Téléversement multimédia invalide.', 'Invalid post ID.': 'Identifiant de publication invalide.', 'Post not found.': 'Publication introuvable.', 'Write a comment first.': 'Écrivez d’abord un commentaire.', 'Comments must be 1,000 characters or fewer.': 'Les commentaires doivent contenir au maximum 1 000 caractères.', 'Invalid comment ID.': 'Identifiant de commentaire invalide.', 'No token': 'Jeton manquant.', 'User not found': 'Utilisateur introuvable.', 'Invalid token': 'Jeton invalide.', 'Choose a profile photo to upload.': 'Choisissez une photo de profil à téléverser.', 'Profile photo uploads are not configured on the server.': 'Le téléversement des photos de profil n’est pas configuré sur le serveur.', 'Unable to update your profile photo.': 'Impossible de mettre à jour votre photo de profil.', 'No valid profile fields provided': 'Aucun champ de profil valide fourni.', 'Profile updated successfully': 'Profil mis à jour avec succès.', 'Profile update failed': 'Échec de la mise à jour du profil.', 'Choose an image file for your profile photo.': 'Choisissez un fichier image pour votre photo de profil.', 'Invalid profile photo.': 'Photo de profil invalide.', 'Invalid user ID.': 'Identifiant utilisateur invalide.', 'Unable to load profile posts.': 'Impossible de charger les publications du profil.',
};

const dutch = {
  'Home': 'Start', 'People': 'Mensen', 'Create': 'Maken', 'Inbox': 'Inbox', 'Profile': 'Profiel', 'Alerts': 'Meldingen', 'Settings': 'Instellingen', 'Back': 'Terug',
  'Account': 'Account', 'No email': 'Geen e-mailadres', 'Appearance': 'Weergave', 'Dark mode': 'Donkere modus', 'Light mode': 'Lichte modus', 'Applies across the entire app': 'Geldt voor de hele app',
  'Language': 'Taal', 'Choose your preferred language': 'Kies je voorkeurstaal', 'Edit Profile': 'Profiel bewerken', 'Log out': 'Uitloggen', 'Log Out': 'Uitloggen', 'Are you sure you want to log out?': 'Weet je zeker dat je wilt uitloggen?', 'Cancel': 'Annuleren', 'Toggle dark mode': 'Donkere modus in- of uitschakelen', 'Select language': 'Taal kiezen', 'Close language selection': 'Taalkeuze sluiten',
  'Welcome back': 'Welkom terug', 'Sign in to continue to Topline.': 'Log in om door te gaan naar Topline.', 'Connect. Share. Stay informed.': 'Maak contact. Deel. Blijf op de hoogte.', 'Email or Username': 'E-mail of gebruikersnaam', 'Enter your email or username': 'Vul je e-mail of gebruikersnaam in', 'Password': 'Wachtwoord', 'Enter your password': 'Vul je wachtwoord in', 'Signing In...': 'Bezig met inloggen...', 'Sign In': 'Inloggen', 'Create Account': 'Account maken',
  'Missing information': 'Ontbrekende gegevens', 'Please enter your email/username and password.': 'Vul je e-mail/gebruikersnaam en wachtwoord in.', 'Login failed': 'Inloggen mislukt', 'Unable to log in.': 'Inloggen is niet mogelijk.', 'Create your account': 'Maak je account', 'Join Topline and connect with others.': 'Word lid van Topline en kom in contact met anderen.', 'Full Name': 'Volledige naam', 'Enter your full name': 'Vul je volledige naam in', 'Username': 'Gebruikersnaam', 'Choose a username': 'Kies een gebruikersnaam', 'Email': 'E-mail', 'Enter your email': 'Vul je e-mailadres in', 'Phone': 'Telefoon', 'Enter your phone number': 'Vul je telefoonnummer in', 'Date of Birth': 'Geboortedatum', 'Create a password': 'Maak een wachtwoord', 'Creating Account...': 'Account wordt gemaakt...', 'Already have an account? Sign In': 'Heb je al een account? Log in',
  'Please fill in all required fields.': 'Vul alle verplichte velden in.', 'Registration failed': 'Registratie mislukt', 'Unable to create your account.': 'Je account kan niet worden aangemaakt.', 'Create Post': 'Bericht maken', 'Post': 'Plaatsen', 'You': 'Jij', 'Everyone can see this post': 'Iedereen kan dit bericht zien', "What's on your mind?": 'Wat houdt je bezig?', 'Add to your post': 'Aan je bericht toevoegen', 'Photo': 'Foto', 'Video': 'Video', 'Video selected': 'Video geselecteerd', 'Photo selected': 'Foto geselecteerd',
  'Permission required': 'Toestemming vereist', 'Allow access to your photos and videos to add media to a post.': 'Geef toegang tot je foto’s en video’s om media aan een bericht toe te voegen.', 'Unable to open media': 'Media kan niet worden geopend', 'Sign in required': 'Inloggen vereist', 'Sign in before creating a post.': 'Log in voordat je een bericht maakt.', 'Post failed': 'Bericht plaatsen mislukt', 'Please try again.': 'Probeer het opnieuw.', 'Remove selected media': 'Geselecteerde media verwijderen',
  'Find people and connect': 'Vind mensen en maak contact', 'Search people...': 'Mensen zoeken...', 'People you may know': 'Mensen die je misschien kent', 'Discover people on Topline': 'Ontdek mensen op Topline', 'Following': 'Volgend', 'Follow': 'Volgen', 'No people found': 'Geen mensen gevonden', 'Try searching for another name or username.': 'Zoek op een andere naam of gebruikersnaam.',
  'Messages': 'Berichten', 'No messages yet': 'Nog geen berichten', 'No conversations yet': 'Nog geen gesprekken', 'Your conversation with {name} will appear here.': 'Je gesprek met {name} verschijnt hier.', 'Your conversations will appear here.': 'Je gesprekken verschijnen hier.', 'Find people': 'Mensen vinden', 'You’re all caught up': 'Je bent helemaal bij', 'Likes, replies, and follows will show up here.': 'Likes, reacties en nieuwe volgers verschijnen hier.', 'Back to feed': 'Terug naar de feed',
  'Comments': 'Reacties', 'No comments yet': 'Nog geen reacties', 'Start the conversation.': 'Begin het gesprek.', 'Add a comment...': 'Reactie toevoegen...', 'Delete comment?': 'Reactie verwijderen?', 'This comment will be removed from the video.': 'Deze reactie wordt van de video verwijderd.', 'Delete': 'Verwijderen', 'Delete your comment': 'Je reactie verwijderen', 'Close comments': 'Reacties sluiten', 'Post comment': 'Reactie plaatsen', 'Just now': 'Zojuist', 'Topline user': 'Topline-gebruiker',
  'Unable to load comments.': 'Reacties kunnen niet worden geladen.', 'Unable to add comment.': 'Reactie toevoegen is niet gelukt.', 'Unable to delete comment.': 'Reactie verwijderen is niet gelukt.', 'Choose or change profile photo': 'Profielfoto kiezen of wijzigen', 'Change profile photo': 'Profielfoto wijzigen', 'Add profile photo': 'Profielfoto toevoegen', 'Allow access to photos to choose a profile picture.': 'Geef toegang tot foto’s om een profielfoto te kiezen.', 'Photo unavailable': 'Foto niet beschikbaar', 'Unable to open your photos.': 'Je foto’s kunnen niet worden geopend.', 'Missing info': 'Ontbrekende gegevens', 'Name and username are required.': 'Naam en gebruikersnaam zijn verplicht.', 'Success': 'Gelukt', 'Your profile has been updated.': 'Je profiel is bijgewerkt.', 'Update failed': 'Bijwerken mislukt', 'Unable to update your profile.': 'Je profiel kan niet worden bijgewerkt.',
  'Tell people about yourself': 'Vertel iets over jezelf', 'Location': 'Locatie', 'City or country': 'Plaats of land', 'Saving...': 'Opslaan...', 'Save Changes': 'Wijzigingen opslaan', 'Topline User': 'Topline-gebruiker', 'Posts': 'Berichten', 'Followers': 'Volgers', 'Message': 'Bericht', 'Edit profile photo': 'Profielfoto bewerken', 'No posts yet': 'Nog geen berichten', 'When this user shares something, it will appear here.': 'Berichten van deze gebruiker verschijnen hier.', 'Recently': 'Onlangs', 'For You': 'Voor jou', 'Open alerts': 'Meldingen openen', 'Open messages': 'Berichten openen', 'Go back': 'Teruggaan', 'Pause posted video': 'Video pauzeren', 'Play posted video': 'Video afspelen', 'Topline app icon': 'Topline-apppictogram', 'Loading...': 'Laden...', 'Bio': 'Bio', 'this person': 'deze persoon', 'View {count} comments': '{count} reacties bekijken',
  'A sample clip for testing video playback.': 'Een voorbeeldclip om videoweergave te testen.', 'Animated trailer sample.': 'Voorbeeld van een animatietrailer.', 'A short animated sample clip.': 'Een korte voorbeeldanimatie.', 'MP4 sample': 'MP4-voorbeeld', 'Video post': 'Videobericht', 'Topline post': 'Topline-bericht', 'Living, learning and sharing.': 'Leven, leren en delen.', 'Creator • Photographer • Traveler': 'Maker • Fotograaf • Reiziger', 'Technology and community.': 'Technologie en gemeenschap.', 'Making a difference every day.': 'Elke dag het verschil maken.', 'Joined recently': 'Onlangs lid geworden', 'Open profile for {name}': 'Profiel van {name} openen',
  'Email or phone required.': 'E-mail of telefoonnummer is verplicht.', 'All fields are required.': 'Alle velden zijn verplicht.', 'Please provide a valid date of birth.': 'Vul een geldige geboortedatum in.', 'Account created successfully.': 'Account succesvol aangemaakt.', 'Something went wrong while creating the account.': 'Er is iets misgegaan bij het aanmaken van het account.', 'Email/username and password are required.': 'E-mail/gebruikersnaam en wachtwoord zijn verplicht.', 'Incorrect email/username or password.': 'E-mail/gebruikersnaam of wachtwoord is onjuist.', 'Something went wrong while logging in.': 'Er is iets misgegaan bij het inloggen.', 'Sign in to create a post.': 'Log in om een bericht te maken.', 'Your session has expired.': 'Je sessie is verlopen.', 'User account was not found.': 'Gebruikersaccount niet gevonden.', 'Add text, a photo, or a video.': 'Voeg tekst, een foto of een video toe.', 'Media uploads are not configured on the server.': 'Media-upload is niet ingesteld op de server.', 'Unable to create post.': 'Bericht maken is niet gelukt.', 'Media files must be 100 MB or smaller.': 'Mediabestanden mogen maximaal 100 MB groot zijn.', 'Invalid media upload.': 'Ongeldige media-upload.', 'Invalid post ID.': 'Ongeldige bericht-ID.', 'Post not found.': 'Bericht niet gevonden.', 'Write a comment first.': 'Schrijf eerst een reactie.', 'Comments must be 1,000 characters or fewer.': 'Reacties mogen maximaal 1.000 tekens bevatten.', 'Invalid comment ID.': 'Ongeldige reactie-ID.', 'No token': 'Geen toegangstoken.', 'User not found': 'Gebruiker niet gevonden.', 'Invalid token': 'Ongeldig toegangstoken.', 'Choose a profile photo to upload.': 'Kies een profielfoto om te uploaden.', 'Profile photo uploads are not configured on the server.': 'Profielfoto-upload is niet ingesteld op de server.', 'Unable to update your profile photo.': 'Je profielfoto kan niet worden bijgewerkt.', 'No valid profile fields provided': 'Geen geldige profielvelden opgegeven.', 'Profile updated successfully': 'Profiel succesvol bijgewerkt.', 'Profile update failed': 'Profiel bijwerken is mislukt.', 'Choose an image file for your profile photo.': 'Kies een afbeeldingsbestand als profielfoto.', 'Invalid profile photo.': 'Ongeldige profielfoto.', 'Invalid user ID.': 'Ongeldige gebruikers-ID.', 'Unable to load profile posts.': 'Profielberichten kunnen niet worden geladen.',
};

const arabic = {
  'Home': 'الرئيسية', 'People': 'الأشخاص', 'Create': 'إنشاء', 'Inbox': 'الوارد', 'Profile': 'الملف الشخصي', 'Alerts': 'التنبيهات', 'Settings': 'الإعدادات', 'Back': 'رجوع',
  'Account': 'الحساب', 'No email': 'لا يوجد بريد إلكتروني', 'Appearance': 'المظهر', 'Dark mode': 'الوضع الداكن', 'Light mode': 'الوضع الفاتح', 'Applies across the entire app': 'يُطبّق على التطبيق بالكامل',
  'Language': 'اللغة', 'Choose your preferred language': 'اختر لغتك المفضلة', 'Edit Profile': 'تعديل الملف الشخصي', 'Log out': 'تسجيل الخروج', 'Log Out': 'تسجيل الخروج', 'Are you sure you want to log out?': 'هل تريد تسجيل الخروج بالتأكيد؟', 'Cancel': 'إلغاء', 'Toggle dark mode': 'تبديل الوضع الداكن', 'Select language': 'اختر اللغة', 'Close language selection': 'إغلاق اختيار اللغة',
  'Welcome back': 'مرحبًا بعودتك', 'Sign in to continue to Topline.': 'سجّل الدخول للمتابعة إلى Topline.', 'Connect. Share. Stay informed.': 'تواصل. شارك. ابقَ على اطلاع.', 'Email or Username': 'البريد الإلكتروني أو اسم المستخدم', 'Enter your email or username': 'أدخل بريدك الإلكتروني أو اسم المستخدم', 'Password': 'كلمة المرور', 'Enter your password': 'أدخل كلمة المرور', 'Signing In...': 'جارٍ تسجيل الدخول...', 'Sign In': 'تسجيل الدخول', 'Create Account': 'إنشاء حساب',
  'Missing information': 'معلومات ناقصة', 'Please enter your email/username and password.': 'أدخل بريدك الإلكتروني أو اسم المستخدم وكلمة المرور.', 'Login failed': 'تعذّر تسجيل الدخول', 'Unable to log in.': 'تعذّر تسجيل الدخول.', 'Create your account': 'أنشئ حسابك', 'Join Topline and connect with others.': 'انضم إلى Topline وتواصل مع الآخرين.', 'Full Name': 'الاسم الكامل', 'Enter your full name': 'أدخل اسمك الكامل', 'Username': 'اسم المستخدم', 'Choose a username': 'اختر اسم مستخدم', 'Email': 'البريد الإلكتروني', 'Enter your email': 'أدخل بريدك الإلكتروني', 'Phone': 'الهاتف', 'Enter your phone number': 'أدخل رقم هاتفك', 'Date of Birth': 'تاريخ الميلاد', 'Create a password': 'أنشئ كلمة مرور', 'Creating Account...': 'جارٍ إنشاء الحساب...', 'Already have an account? Sign In': 'لديك حساب بالفعل؟ سجّل الدخول',
  'Please fill in all required fields.': 'يرجى ملء جميع الحقول المطلوبة.', 'Registration failed': 'فشل التسجيل', 'Unable to create your account.': 'تعذّر إنشاء حسابك.', 'Create Post': 'إنشاء منشور', 'Post': 'نشر', 'You': 'أنت', 'Everyone can see this post': 'يمكن للجميع رؤية هذا المنشور', "What's on your mind?": 'بماذا تفكر؟', 'Add to your post': 'أضف إلى منشورك', 'Photo': 'صورة', 'Video': 'فيديو', 'Video selected': 'تم اختيار الفيديو', 'Photo selected': 'تم اختيار الصورة',
  'Permission required': 'الإذن مطلوب', 'Allow access to your photos and videos to add media to a post.': 'اسمح بالوصول إلى الصور ومقاطع الفيديو لإضافتها إلى المنشور.', 'Unable to open media': 'تعذّر فتح الوسائط', 'Sign in required': 'يلزم تسجيل الدخول', 'Sign in before creating a post.': 'سجّل الدخول قبل إنشاء منشور.', 'Post failed': 'فشل نشر المنشور', 'Please try again.': 'يرجى المحاولة مرة أخرى.', 'Remove selected media': 'إزالة الوسائط المحددة',
  'Find people and connect': 'ابحث عن أشخاص وتواصل معهم', 'Search people...': 'ابحث عن أشخاص...', 'People you may know': 'أشخاص قد تعرفهم', 'Discover people on Topline': 'اكتشف أشخاصًا على Topline', 'Following': 'تتابعهم', 'Follow': 'متابعة', 'No people found': 'لم يتم العثور على أشخاص', 'Try searching for another name or username.': 'جرّب البحث عن اسم أو اسم مستخدم آخر.',
  'Messages': 'الرسائل', 'No messages yet': 'لا توجد رسائل بعد', 'No conversations yet': 'لا توجد محادثات بعد', 'Your conversation with {name} will appear here.': 'ستظهر محادثتك مع {name} هنا.', 'Your conversations will appear here.': 'ستظهر محادثاتك هنا.', 'Find people': 'ابحث عن أشخاص', 'You’re all caught up': 'لقد اطلعت على كل شيء', 'Likes, replies, and follows will show up here.': 'ستظهر الإعجابات والردود والمتابعات هنا.', 'Back to feed': 'العودة إلى المنشورات',
  'Comments': 'التعليقات', 'No comments yet': 'لا توجد تعليقات بعد', 'Start the conversation.': 'ابدأ المحادثة.', 'Add a comment...': 'أضف تعليقًا...', 'Delete comment?': 'هل تريد حذف التعليق؟', 'This comment will be removed from the video.': 'ستتم إزالة هذا التعليق من الفيديو.', 'Delete': 'حذف', 'Delete your comment': 'حذف تعليقك', 'Close comments': 'إغلاق التعليقات', 'Post comment': 'نشر التعليق', 'Just now': 'الآن', 'Topline user': 'مستخدم Topline',
  'Unable to load comments.': 'تعذّر تحميل التعليقات.', 'Unable to add comment.': 'تعذّر إضافة التعليق.', 'Unable to delete comment.': 'تعذّر حذف التعليق.', 'Choose or change profile photo': 'اختر صورة الملف الشخصي أو غيّرها', 'Change profile photo': 'تغيير صورة الملف الشخصي', 'Add profile photo': 'إضافة صورة للملف الشخصي', 'Allow access to photos to choose a profile picture.': 'اسمح بالوصول إلى الصور لاختيار صورة للملف الشخصي.', 'Photo unavailable': 'الصورة غير متاحة', 'Unable to open your photos.': 'تعذّر فتح صورك.', 'Missing info': 'معلومات ناقصة', 'Name and username are required.': 'الاسم واسم المستخدم مطلوبان.', 'Success': 'تم بنجاح', 'Your profile has been updated.': 'تم تحديث ملفك الشخصي.', 'Update failed': 'فشل التحديث', 'Unable to update your profile.': 'تعذّر تحديث ملفك الشخصي.',
  'Tell people about yourself': 'أخبر الآخرين عن نفسك', 'Location': 'الموقع', 'City or country': 'المدينة أو الدولة', 'Saving...': 'جارٍ الحفظ...', 'Save Changes': 'حفظ التغييرات', 'Topline User': 'مستخدم Topline', 'Posts': 'المنشورات', 'Followers': 'المتابعون', 'Message': 'رسالة', 'Edit profile photo': 'تعديل صورة الملف الشخصي', 'No posts yet': 'لا توجد منشورات بعد', 'When this user shares something, it will appear here.': 'ستظهر منشورات هذا المستخدم هنا.', 'Recently': 'مؤخرًا', 'For You': 'لك', 'Open alerts': 'فتح التنبيهات', 'Open messages': 'فتح الرسائل', 'Go back': 'رجوع', 'Pause posted video': 'إيقاف الفيديو مؤقتًا', 'Play posted video': 'تشغيل الفيديو المنشور', 'Topline app icon': 'أيقونة تطبيق Topline', 'Loading...': 'جارٍ التحميل...', 'Bio': 'نبذة', 'this person': 'هذا الشخص', 'View {count} comments': 'عرض {count} من التعليقات',
  'A sample clip for testing video playback.': 'مقطع تجريبي لاختبار تشغيل الفيديو.', 'Animated trailer sample.': 'مقطع دعائي تجريبي متحرك.', 'A short animated sample clip.': 'مقطع تجريبي قصير متحرك.', 'MP4 sample': 'نموذج MP4', 'Video post': 'منشور فيديو', 'Topline post': 'منشور Topline', 'Living, learning and sharing.': 'نعيش ونتعلم ونتشارك.', 'Creator • Photographer • Traveler': 'مبدع • مصور • مسافر', 'Technology and community.': 'التقنية والمجتمع.', 'Making a difference every day.': 'نصنع فرقًا كل يوم.', 'Joined recently': 'انضم مؤخرًا', 'Open profile for {name}': 'فتح الملف الشخصي لـ {name}',
  'Email or phone required.': 'البريد الإلكتروني أو الهاتف مطلوب.', 'All fields are required.': 'جميع الحقول مطلوبة.', 'Please provide a valid date of birth.': 'يرجى إدخال تاريخ ميلاد صحيح.', 'Account created successfully.': 'تم إنشاء الحساب بنجاح.', 'Something went wrong while creating the account.': 'حدث خطأ أثناء إنشاء الحساب.', 'Email/username and password are required.': 'البريد الإلكتروني أو اسم المستخدم وكلمة المرور مطلوبة.', 'Incorrect email/username or password.': 'البريد الإلكتروني أو اسم المستخدم أو كلمة المرور غير صحيحة.', 'Something went wrong while logging in.': 'حدث خطأ أثناء تسجيل الدخول.', 'Sign in to create a post.': 'سجّل الدخول لإنشاء منشور.', 'Your session has expired.': 'انتهت صلاحية جلستك.', 'User account was not found.': 'لم يتم العثور على حساب المستخدم.', 'Add text, a photo, or a video.': 'أضف نصًا أو صورة أو فيديو.', 'Media uploads are not configured on the server.': 'رفع الوسائط غير مُعد على الخادم.', 'Unable to create post.': 'تعذّر إنشاء المنشور.', 'Media files must be 100 MB or smaller.': 'يجب ألا يتجاوز حجم ملفات الوسائط 100 ميغابايت.', 'Invalid media upload.': 'رفع الوسائط غير صالح.', 'Invalid post ID.': 'معرّف المنشور غير صالح.', 'Post not found.': 'لم يتم العثور على المنشور.', 'Write a comment first.': 'اكتب تعليقًا أولًا.', 'Comments must be 1,000 characters or fewer.': 'يجب ألا يتجاوز التعليق 1000 حرف.', 'Invalid comment ID.': 'معرّف التعليق غير صالح.', 'No token': 'رمز الدخول غير موجود.', 'User not found': 'لم يتم العثور على المستخدم.', 'Invalid token': 'رمز الدخول غير صالح.', 'Choose a profile photo to upload.': 'اختر صورة للملف الشخصي لرفعها.', 'Profile photo uploads are not configured on the server.': 'رفع صور الملفات الشخصية غير مُعد على الخادم.', 'Unable to update your profile photo.': 'تعذّر تحديث صورة ملفك الشخصي.', 'No valid profile fields provided': 'لم يتم إدخال حقول ملف شخصي صالحة.', 'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح.', 'Profile update failed': 'فشل تحديث الملف الشخصي.', 'Choose an image file for your profile photo.': 'اختر ملف صورة لصورة ملفك الشخصي.', 'Invalid profile photo.': 'صورة الملف الشخصي غير صالحة.', 'Invalid user ID.': 'معرّف المستخدم غير صالح.', 'Unable to load profile posts.': 'تعذّر تحميل منشورات الملف الشخصي.',
};

const spanish = {
  'Home': 'Inicio', 'People': 'Personas', 'Create': 'Crear', 'Inbox': 'Bandeja', 'Profile': 'Perfil', 'Alerts': 'Avisos', 'Settings': 'Ajustes', 'Back': 'Volver',
  'Account': 'Cuenta', 'No email': 'Sin correo electrónico', 'Appearance': 'Apariencia', 'Dark mode': 'Modo oscuro', 'Light mode': 'Modo claro', 'Applies across the entire app': 'Se aplica a toda la aplicación',
  'Language': 'Idioma', 'Choose your preferred language': 'Elige tu idioma preferido', 'Edit Profile': 'Editar perfil', 'Log out': 'Cerrar sesión', 'Log Out': 'Cerrar sesión', 'Are you sure you want to log out?': '¿Seguro que quieres cerrar sesión?', 'Cancel': 'Cancelar', 'Toggle dark mode': 'Activar o desactivar el modo oscuro', 'Select language': 'Seleccionar idioma', 'Close language selection': 'Cerrar selección de idioma',
  'Welcome back': 'Te damos la bienvenida', 'Sign in to continue to Topline.': 'Inicia sesión para continuar en Topline.', 'Connect. Share. Stay informed.': 'Conecta. Comparte. Mantente al día.', 'Email or Username': 'Correo o nombre de usuario', 'Enter your email or username': 'Escribe tu correo o nombre de usuario', 'Password': 'Contraseña', 'Enter your password': 'Escribe tu contraseña', 'Signing In...': 'Iniciando sesión...', 'Sign In': 'Iniciar sesión', 'Create Account': 'Crear cuenta',
  'Missing information': 'Falta información', 'Please enter your email/username and password.': 'Escribe tu correo/nombre de usuario y contraseña.', 'Login failed': 'No se pudo iniciar sesión', 'Unable to log in.': 'No se pudo iniciar sesión.', 'Create your account': 'Crea tu cuenta', 'Join Topline and connect with others.': 'Únete a Topline y conecta con otras personas.', 'Full Name': 'Nombre completo', 'Enter your full name': 'Escribe tu nombre completo', 'Username': 'Nombre de usuario', 'Choose a username': 'Elige un nombre de usuario', 'Email': 'Correo electrónico', 'Enter your email': 'Escribe tu correo electrónico', 'Phone': 'Teléfono', 'Enter your phone number': 'Escribe tu número de teléfono', 'Date of Birth': 'Fecha de nacimiento', 'Create a password': 'Crea una contraseña', 'Creating Account...': 'Creando cuenta...', 'Already have an account? Sign In': '¿Ya tienes una cuenta? Inicia sesión',
  'Please fill in all required fields.': 'Completa todos los campos obligatorios.', 'Registration failed': 'No se pudo completar el registro', 'Unable to create your account.': 'No se pudo crear tu cuenta.', 'Create Post': 'Crear publicación', 'Post': 'Publicar', 'You': 'Tú', 'Everyone can see this post': 'Todo el mundo puede ver esta publicación', "What's on your mind?": '¿Qué tienes en mente?', 'Add to your post': 'Añadir a tu publicación', 'Photo': 'Foto', 'Video': 'Vídeo', 'Video selected': 'Vídeo seleccionado', 'Photo selected': 'Foto seleccionada',
  'Permission required': 'Se necesita permiso', 'Allow access to your photos and videos to add media to a post.': 'Permite el acceso a tus fotos y vídeos para añadir contenido a una publicación.', 'Unable to open media': 'No se pudo abrir el archivo', 'Sign in required': 'Se requiere iniciar sesión', 'Sign in before creating a post.': 'Inicia sesión antes de crear una publicación.', 'Post failed': 'No se pudo publicar', 'Please try again.': 'Vuelve a intentarlo.', 'Remove selected media': 'Quitar el archivo seleccionado',
  'Find people and connect': 'Encuentra personas y conecta', 'Search people...': 'Buscar personas...', 'People you may know': 'Personas que quizá conozcas', 'Discover people on Topline': 'Descubre personas en Topline', 'Following': 'Siguiendo', 'Follow': 'Seguir', 'No people found': 'No se encontraron personas', 'Try searching for another name or username.': 'Prueba con otro nombre o nombre de usuario.',
  'Messages': 'Mensajes', 'No messages yet': 'Todavía no hay mensajes', 'No conversations yet': 'Todavía no hay conversaciones', 'Your conversation with {name} will appear here.': 'Tu conversación con {name} aparecerá aquí.', 'Your conversations will appear here.': 'Tus conversaciones aparecerán aquí.', 'Find people': 'Buscar personas', 'You’re all caught up': 'Ya estás al día', 'Likes, replies, and follows will show up here.': 'Aquí aparecerán los Me gusta, las respuestas y los nuevos seguidores.', 'Back to feed': 'Volver al inicio',
  'Comments': 'Comentarios', 'No comments yet': 'Todavía no hay comentarios', 'Start the conversation.': 'Inicia la conversación.', 'Add a comment...': 'Añadir un comentario...', 'Delete comment?': '¿Eliminar comentario?', 'This comment will be removed from the video.': 'Este comentario se eliminará del vídeo.', 'Delete': 'Eliminar', 'Delete your comment': 'Eliminar tu comentario', 'Close comments': 'Cerrar comentarios', 'Post comment': 'Publicar comentario', 'Just now': 'Ahora mismo', 'Topline user': 'Usuario de Topline',
  'Unable to load comments.': 'No se pudieron cargar los comentarios.', 'Unable to add comment.': 'No se pudo añadir el comentario.', 'Unable to delete comment.': 'No se pudo eliminar el comentario.', 'Choose or change profile photo': 'Elegir o cambiar foto de perfil', 'Change profile photo': 'Cambiar foto de perfil', 'Add profile photo': 'Añadir foto de perfil', 'Allow access to photos to choose a profile picture.': 'Permite el acceso a las fotos para elegir una foto de perfil.', 'Photo unavailable': 'Foto no disponible', 'Unable to open your photos.': 'No se pudieron abrir tus fotos.', 'Missing info': 'Falta información', 'Name and username are required.': 'El nombre y el nombre de usuario son obligatorios.', 'Success': 'Listo', 'Your profile has been updated.': 'Tu perfil se ha actualizado.', 'Update failed': 'No se pudo actualizar', 'Unable to update your profile.': 'No se pudo actualizar tu perfil.',
  'Tell people about yourself': 'Cuéntales a los demás sobre ti', 'Location': 'Ubicación', 'City or country': 'Ciudad o país', 'Saving...': 'Guardando...', 'Save Changes': 'Guardar cambios', 'Topline User': 'Usuario de Topline', 'Posts': 'Publicaciones', 'Followers': 'Seguidores', 'Message': 'Mensaje', 'Edit profile photo': 'Editar foto de perfil', 'No posts yet': 'Todavía no hay publicaciones', 'When this user shares something, it will appear here.': 'Las publicaciones de esta persona aparecerán aquí.', 'Recently': 'Recientemente', 'For You': 'Para ti', 'Open alerts': 'Abrir avisos', 'Open messages': 'Abrir mensajes', 'Go back': 'Volver', 'Pause posted video': 'Pausar vídeo', 'Play posted video': 'Reproducir vídeo', 'Topline app icon': 'Icono de la aplicación Topline', 'Loading...': 'Cargando...', 'Bio': 'Biografía', 'this person': 'esta persona', 'View {count} comments': 'Ver {count} comentarios',
  'A sample clip for testing video playback.': 'Un clip de ejemplo para probar la reproducción de vídeo.', 'Animated trailer sample.': 'Tráiler animado de ejemplo.', 'A short animated sample clip.': 'Un breve clip animado de ejemplo.', 'MP4 sample': 'Ejemplo MP4', 'Video post': 'Publicación de vídeo', 'Topline post': 'Publicación de Topline', 'Living, learning and sharing.': 'Vivir, aprender y compartir.', 'Creator • Photographer • Traveler': 'Creador • Fotógrafo • Viajero', 'Technology and community.': 'Tecnología y comunidad.', 'Making a difference every day.': 'Marcando la diferencia cada día.', 'Joined recently': 'Se unió recientemente', 'Open profile for {name}': 'Abrir el perfil de {name}',
  'Email or phone required.': 'Se requiere correo electrónico o teléfono.', 'All fields are required.': 'Todos los campos son obligatorios.', 'Please provide a valid date of birth.': 'Introduce una fecha de nacimiento válida.', 'Account created successfully.': 'La cuenta se creó correctamente.', 'Something went wrong while creating the account.': 'Se produjo un error al crear la cuenta.', 'Email/username and password are required.': 'El correo/nombre de usuario y la contraseña son obligatorios.', 'Incorrect email/username or password.': 'El correo/nombre de usuario o la contraseña no son correctos.', 'Something went wrong while logging in.': 'Se produjo un error al iniciar sesión.', 'Sign in to create a post.': 'Inicia sesión para crear una publicación.', 'Your session has expired.': 'Tu sesión ha caducado.', 'User account was not found.': 'No se encontró la cuenta de usuario.', 'Add text, a photo, or a video.': 'Añade texto, una foto o un vídeo.', 'Media uploads are not configured on the server.': 'La carga de archivos multimedia no está configurada en el servidor.', 'Unable to create post.': 'No se pudo crear la publicación.', 'Media files must be 100 MB or smaller.': 'Los archivos multimedia deben ocupar 100 MB o menos.', 'Invalid media upload.': 'La carga multimedia no es válida.', 'Invalid post ID.': 'El identificador de la publicación no es válido.', 'Post not found.': 'No se encontró la publicación.', 'Write a comment first.': 'Escribe un comentario primero.', 'Comments must be 1,000 characters or fewer.': 'Los comentarios deben tener 1.000 caracteres o menos.', 'Invalid comment ID.': 'El identificador del comentario no es válido.', 'No token': 'Falta el token.', 'User not found': 'No se encontró el usuario.', 'Invalid token': 'El token no es válido.', 'Choose a profile photo to upload.': 'Elige una foto de perfil para subirla.', 'Profile photo uploads are not configured on the server.': 'La carga de fotos de perfil no está configurada en el servidor.', 'Unable to update your profile photo.': 'No se pudo actualizar tu foto de perfil.', 'No valid profile fields provided': 'No se proporcionaron campos de perfil válidos.', 'Profile updated successfully': 'El perfil se actualizó correctamente.', 'Profile update failed': 'No se pudo actualizar el perfil.', 'Choose an image file for your profile photo.': 'Elige un archivo de imagen para tu foto de perfil.', 'Invalid profile photo.': 'La foto de perfil no es válida.', 'Invalid user ID.': 'El identificador de usuario no es válido.', 'Unable to load profile posts.': 'No se pudieron cargar las publicaciones del perfil.',
};

const catalogs = { en: {}, sw: swahili, fr: french, nl: dutch, ar: arabic, es: spanish };

export const supportedLanguages = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'sw', name: 'Kiswahili', nativeName: 'Kiswahili' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
];

export const languageLocales = {
  en: 'en',
  sw: 'sw-KE',
  fr: 'fr-FR',
  nl: 'nl-NL',
  ar: 'ar',
  es: 'es-ES',
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [ready, setReady] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY)
      .then((savedLanguage) => {
        if (supportedLanguages.some(({ code }) => code === savedLanguage)) {
          setLanguageState(savedLanguage);
        }
      })
      .catch((error) => console.warn('Could not load saved language:', error))
      .finally(() => setReady(true));
  }, []);

  const setLanguage = async (nextLanguage) => {
    if (!supportedLanguages.some(({ code }) => code === nextLanguage)) return;
    setLanguageState(nextLanguage);
    try {
      await AsyncStorage.setItem(LANGUAGE_KEY, nextLanguage);
    } catch (error) {
      console.warn('Could not save selected language:', error);
    }
  };

  const t = useCallback((key, values = {}) => {
    let translation = catalogs[language][key] || key;
    Object.entries(values).forEach(([name, value]) => {
      translation = translation.replaceAll(`{${name}}`, String(value));
    });
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, supportedLanguages, ready }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
